Repository ON-AIR-mate/Node.js, pull requests merged in 2025-08, with the labels that each got.

#78 feat: 방 기존 설정 값 가져오는 api 구현
  src/controllers/roomSettingController.ts
  src/dtos/youtubeRecommendationDto.ts
  src/routes/roomRoute.ts
  src/services/roomSettingService.ts
  src/services/youtubeRecommendationService.ts
Labels: ✨feature

#79 feat: 활성화된 방 목록 조회 api 일부 수정
  src/controllers/activeRoomsController.ts
  src/routes/activeRoomsRoute.ts
  src/routes/roomRoute.ts
  src/services/activeRoomsService.ts
Labels: ✨feature

#80 Feat/s3 upload
  .gitignore
  package-lock.json
  package.json
  src/config/s3Config.ts
  src/constants/errorCodes.ts
  src/controllers/authController.ts
  src/controllers/userController.ts
  src/dtos/activeRoomsDto.ts
  src/middleware/authValidation.ts
  src/middleware/uploadMiddleware.ts
  src/routes/userRoutes.ts
  src/utils/s3utils.ts
  tsconfig.json
Labels: ✨feature, 🔨refactor

#81 Feat/ai summary
  package-lock.json
  package.json
  src/app.ts
  src/controllers/aiSummaryController.ts
  src/controllers/authController.ts
  src/controllers/userController.ts
  src/dtos/aiSummaryDto.ts
  src/middleware/uploadMiddleware.ts
  src/routes/aiSummaryRoutes.ts
  src/routes/userRoutes.ts
  src/services/aiSummaryService.ts
  src/utils/s3utils.ts
  tsconfig.json
Labels: ✨feature

#67 Feature: 사용자 recommendation 관련 api 구현
  package-lock.json
  prisma/migrations/20250725072024_add_optional_video_id/migration.sql
  prisma/migrations/20250725074316_make_video_id_required/migration.sql
  prisma/migrations/20250730072811_add_timeline_and_start_fields/migration.sql
  prisma/migrations/20250731114836_new_schema/migration.sql
  src/controllers/userRecommendationController.ts
  src/dtos/userRecommendationDto.ts
  src/routes/userRecommendationRoute.ts
  src/services/userRecommendationService.ts
Labels: ✨feature

#72 Feature: sharedCollection 목록 조회 api 구현
  package-lock.json
  src/app.ts
  src/controllers/sharedCollectionController.ts
  src/dtos/sharedCollectionDto.ts
  src/routes/sharedCollectionRoute.ts
  src/services/sharedCollectionService.ts
Labels: ✨feature

#84 fix: 방 생성 api 필드 및 일부 코드 수정
  prisma/schema.prisma
  src/controllers/roomController.ts
  src/dtos/roomDto.ts
  src/routes/activeRoomsRoute.ts
  src/routes/roomRoute.ts
  src/services/roomServices.ts
  src/swagger.ts
Labels: 🐞fix

#89 refactor: 활성화된 방 목록 api 코드 리팩토링 및 테스트
  src/controllers/activeRoomsController.ts
  src/routes/activeRoomsRoute.ts
  src/services/activeRoomsService.ts
  src/swagger.ts
Labels: 🔨refactor

#91 feat: 컬렉션 생성 api 구현
  src/app.ts
  src/controllers/collectionController.ts
  src/dtos/collectionDto.ts
  src/routes/collectionRoutes.ts
  src/services/collectionService.ts
  src/swagger.ts
Labels: ✨feature

#100 Feat: Nginx
  README.md
  src/app.ts
  src/swagger.ts
Labels: ✨feature

#102 Feat: 도메인 설정, HTTPS 강제
  src/app.ts
Labels: ✨feature

#104 feat: 사용자의 컬렉션 목록 조회 api 구현
  src/app.ts
  src/controllers/collectionController.ts
  src/dtos/collectionDto.ts
  src/routes/collectionRoutes.ts
  src/services/collectionService.ts
  src/swagger.ts
Labels: ✨feature

#106 feat: 특정 컬렉션 상세 정보 및 북마크 조회 api 구현
  src/controllers/collectionController.ts
  src/dtos/collectionDto.ts
  src/routes/collectionRoutes.ts
  src/services/collectionService.ts
  src/swagger.ts
Labels: ✨feature

#115 feature: 컬렉션 api - 컬렉션 수정, 컬렉션 순서 변경
  package-lock.json
  prisma/schema.prisma
  src/controllers/collectionController.ts
  src/dtos/collectionDto.ts
  src/routes/collectionRoutes.ts
  src/services/collectionService.ts
Labels: ✨feature

#117 feat(bookmarks): 북마크 목록 조회 응답에 roomName 추가
  src/routes/bookmarkRoute.ts
  src/services/bookmarkService.ts
Labels: ✨feature

#126 Fix: 사용자 추천 가능 여부 확인 api 로직 수정
  src/routes/userRecommendationRoute.ts
  src/services/userRecommendationService.ts
Labels: 🐞fix
